# Generated by Django 3.0.4 on 2020-03-12 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_candidates', models.IntegerField(default=0)),
                ('course_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InvigilatorTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Course')),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examiner', to='crud.Lecturer')),
                ('invigilator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator', to='crud.Lecturer')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Venue')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='examiner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Lecturer'),
        ),
    ]
